name: Check Version and Notify of PGSharp

on:
  schedule:
    - cron: '0 8 * * *' # 
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.43

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Download last version info
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: last-version-info
          path: ${{ github.workspace }}
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          
      - name: Run script
        run: bun dist/index.js
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          VERSION_DISPLAY_PAGE_URL: ${{ secrets.VERSION_DISPLAY_PAGE_URL }}
          APK_DOWNLOAD_API_URL: ${{ secrets.APK_DOWNLOAD_API_URL }}

      - name: Upload current version info artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: last-version-info
          path: ${{ github.workspace }}/last_checked_version.json
          retention-days: 90